// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Traveller.Data;

namespace Traveller.Migrations
{
    [DbContext(typeof(TravellerContext))]
    [Migration("20210305191022_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Traveller.Models.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Atmosphere")
                        .HasColumnType("int");

                    b.Property<string>("Atmosphere_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Government")
                        .HasColumnType("int");

                    b.Property<string>("Government_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Government_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hydrographic_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hydrology")
                        .HasColumnType("int");

                    b.Property<bool>("Imperial_Base")
                        .HasColumnType("bit");

                    b.Property<int>("Law_Level")
                        .HasColumnType("int");

                    b.Property<bool>("Naval_Base")
                        .HasColumnType("bit");

                    b.Property<bool>("Pirate_Base")
                        .HasColumnType("bit");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<string>("Population_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Research_Base")
                        .HasColumnType("bit");

                    b.Property<bool>("Scout_Base")
                        .HasColumnType("bit");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Size_As_Km")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size_CSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Starport")
                        .HasColumnType("int");

                    b.Property<string>("Surface_CSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surface_Gravity_As_Double")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TAS_Base")
                        .HasColumnType("bit");

                    b.Property<int>("Technology_Level")
                        .HasColumnType("int");

                    b.Property<string>("Technology_Level_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Planet");
                });
#pragma warning restore 612, 618
        }
    }
}
